// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../../../';
import Cloudflare from 'cloudflare';

export const metadata: Metadata = {
  resource: 'workers.scripts.versions',
  operation: 'write',
  tags: [],
};

export const tool: Tool = {
  name: 'create_scripts_workers_versions',
  description:
    "Upload a Worker Version without deploying to Cloudflare's network. You can find more about the multipart metadata on our docs: https://developers.cloudflare.com/workers/configuration/multipart-upload-metadata/.",
  inputSchema: {
    type: 'object',
    properties: {
      account_id: {
        type: 'string',
        description: 'Identifier.',
      },
      script_name: {
        type: 'string',
        description: 'Name of the script.',
      },
      metadata: {
        type: 'object',
        description: 'JSON encoded metadata about the uploaded parts and Worker configuration.',
        properties: {
          main_module: {
            type: 'string',
            description:
              'Name of the part in the multipart request that contains the main module (e.g. the file exporting a `fetch` handler). Indicates a `module syntax` Worker, which is required for Version Upload.',
          },
          annotations: {
            type: 'object',
            properties: {
              'workers/message': {
                type: 'string',
                description: 'Human-readable message about the version. Truncated to 100 bytes.',
              },
              'workers/tag': {
                type: 'string',
                description: 'User-provided identifier for the version.',
              },
            },
            required: [],
          },
          bindings: {
            type: 'array',
            description:
              'List of bindings attached to a Worker. You can find more about bindings on our docs: https://developers.cloudflare.com/workers/configuration/multipart-upload-metadata/#bindings.',
            items: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    dataset: {
                      type: 'string',
                      description: 'The name of the dataset to bind to.',
                    },
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['dataset', 'name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                      description: 'Identifier of the D1 database to bind to.',
                    },
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['id', 'name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    namespace: {
                      type: 'string',
                      description: 'Namespace to bind to.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                    outbound: {
                      type: 'object',
                      description: 'Outbound worker.',
                      properties: {
                        params: {
                          type: 'array',
                          description:
                            'Pass information from the Dispatch Worker to the Outbound Worker through the parameters.',
                          items: {
                            type: 'string',
                          },
                        },
                        worker: {
                          type: 'object',
                          description: 'Outbound worker.',
                          properties: {
                            environment: {
                              type: 'string',
                              description: 'Environment of the outbound worker.',
                            },
                            service: {
                              type: 'string',
                              description: 'Name of the outbound worker.',
                            },
                          },
                          required: [],
                        },
                      },
                      required: [],
                    },
                  },
                  required: ['name', 'namespace', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    class_name: {
                      type: 'string',
                      description: 'The exported class name of the Durable Object.',
                    },
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                    environment: {
                      type: 'string',
                      description: 'The environment of the script_name to bind to.',
                    },
                    namespace_id: {
                      type: 'string',
                      description: 'Namespace identifier tag.',
                    },
                    script_name: {
                      type: 'string',
                      description:
                        'The script where the Durable Object is defined, if it is external to this Worker.',
                    },
                  },
                  required: ['class_name', 'name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                      description: 'Identifier of the Hyperdrive connection to bind to.',
                    },
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['id', 'name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    json: {
                      type: 'string',
                      description: 'JSON data to use.',
                    },
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['json', 'name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    namespace_id: {
                      type: 'string',
                      description: 'Namespace identifier tag.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['name', 'namespace_id', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    certificate_id: {
                      type: 'string',
                      description: 'Identifier of the certificate to bind to.',
                    },
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['certificate_id', 'name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    text: {
                      type: 'string',
                      description: 'The text value to use.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['name', 'text', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    queue_name: {
                      type: 'string',
                      description: 'Name of the Queue to bind to.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['name', 'queue_name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    bucket_name: {
                      type: 'string',
                      description: 'R2 bucket to bind to.',
                    },
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['bucket_name', 'name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    text: {
                      type: 'string',
                      description: 'The secret value to use.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['name', 'text', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    environment: {
                      type: 'string',
                      description: 'Optional environment if the Worker utilizes one.',
                    },
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    service: {
                      type: 'string',
                      description: 'Name of Worker to bind to.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['environment', 'name', 'service', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    service: {
                      type: 'string',
                      description: 'Name of Tail Worker to bind to.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['name', 'service', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    index_name: {
                      type: 'string',
                      description: 'Name of the Vectorize index to bind to.',
                    },
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['index_name', 'name', 'type'],
                },
                {
                  type: 'object',
                  properties: {
                    name: {
                      type: 'string',
                      description: 'A JavaScript variable name for the binding.',
                    },
                    type: {
                      type: 'string',
                      description: 'The kind of resource that the binding provides.',
                      enum: [
                        'ai',
                        'analytics_engine',
                        'assets',
                        'browser_rendering',
                        'd1',
                        'dispatch_namespace',
                        'durable_object_namespace',
                        'hyperdrive',
                        'json',
                        'kv_namespace',
                        'mtls_certificate',
                        'plain_text',
                        'queue',
                        'r2_bucket',
                        'secret_text',
                        'service',
                        'tail_consumer',
                        'vectorize',
                        'version_metadata',
                      ],
                    },
                  },
                  required: ['name', 'type'],
                },
              ],
              description: 'A binding to allow the Worker to communicate with resources',
            },
          },
          compatibility_date: {
            type: 'string',
            description:
              'Date indicating targeted support in the Workers runtime. Backwards incompatible fixes to the runtime following this date will not affect this Worker.',
          },
          compatibility_flags: {
            type: 'array',
            description:
              'Flags that enable or disable certain features in the Workers runtime. Used to enable upcoming features or opt in or out of specific changes not included in a `compatibility_date`.',
            items: {
              type: 'string',
              description: 'Flag that enables or disables a specific feature in the Workers runtime.',
            },
          },
          keep_bindings: {
            type: 'array',
            description: 'List of binding types to keep from previous_upload.',
            items: {
              type: 'string',
            },
          },
          usage_model: {
            type: 'string',
            description: 'Usage model for the Worker invocations.',
            enum: ['standard'],
          },
        },
        required: ['main_module'],
      },
    },
  },
};

export const handler = (client: Cloudflare, args: any) => {
  const { script_name, ...body } = args;
  return client.workers.scripts.versions.create(script_name, body);
};

export default { metadata, tool, handler };
