// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import Cloudflare from 'cloudflare';

export const metadata: Metadata = {
  resource: 'ai',
  operation: 'write',
  tags: [],
};

export const tool: Tool = {
  name: 'run_ai',
  description:
    'This endpoint provides users with the capability to run specific AI models on-demand.\n\nBy submitting the required input data, users can receive real-time predictions or results generated by the chosen AI\nmodel. The endpoint supports various AI model types, ensuring flexibility and adaptability for diverse use cases.\n\nModel specific inputs available in [Cloudflare Docs](https://developers.cloudflare.com/workers-ai/models/).',
  inputSchema: {
    type: 'object',
    anyOf: [
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          text: {
            type: 'string',
            description: 'The text that you want to classify',
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          prompt: {
            type: 'string',
            description: 'A text description of the image you want to generate',
          },
          guidance: {
            type: 'number',
            description:
              'Controls how closely the generated image should adhere to the prompt; higher values make the image more aligned with the prompt',
          },
          height: {
            type: 'integer',
            description: 'The height of the generated image in pixels',
          },
          image: {
            type: 'array',
            description:
              'For use with img2img tasks. An array of integers that represent the image data constrained to 8-bit unsigned integer values',
            items: {
              type: 'number',
              description: 'A value between 0 and 255',
            },
          },
          image_b64: {
            type: 'string',
            description: 'For use with img2img tasks. A base64-encoded string of the input image',
          },
          mask: {
            type: 'array',
            description:
              'An array representing An array of integers that represent mask image data for inpainting constrained to 8-bit unsigned integer values',
            items: {
              type: 'number',
              description: 'A value between 0 and 255',
            },
          },
          negative_prompt: {
            type: 'string',
            description: 'Text describing elements to avoid in the generated image',
          },
          num_steps: {
            type: 'integer',
            description: 'The number of diffusion steps; higher values can improve quality but take longer',
          },
          seed: {
            type: 'integer',
            description: 'Random seed for reproducibility of the image generation',
          },
          strength: {
            type: 'number',
            description:
              'A value between 0 and 1 indicating how strongly to apply the transformation during img2img tasks; lower values make the output closer to the input image',
          },
          width: {
            type: 'integer',
            description: 'The width of the generated image in pixels',
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          prompt: {
            type: 'string',
            description: 'A text description of the audio you want to generate',
          },
          lang: {
            type: 'string',
            description:
              "The speech language (e.g., 'en' for English, 'fr' for French). Defaults to 'en' if not specified",
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          text: {
            anyOf: [
              {
                type: 'string',
                description: 'The text to embed',
              },
              {
                type: 'array',
                description: 'Batch of text values to embed',
                items: {
                  type: 'string',
                  description: 'The text to embed',
                },
              },
            ],
            description: 'The text to embed',
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          audio: {
            type: 'array',
            description:
              'An array of integers that represent the audio data constrained to 8-bit unsigned integer values',
            items: {
              type: 'number',
              description: 'A value between 0 and 255',
            },
          },
          source_lang: {
            type: 'string',
            description: 'The language of the recorded audio',
          },
          target_lang: {
            type: 'string',
            description:
              'The language to translate the transcription into. Currently only English is supported.',
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          image: {
            type: 'array',
            description:
              'An array of integers that represent the image data constrained to 8-bit unsigned integer values',
            items: {
              type: 'number',
              description: 'A value between 0 and 255 (unsigned 8bit)',
            },
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          image: {
            type: 'array',
            description:
              'An array of integers that represent the image data constrained to 8-bit unsigned integer values',
            items: {
              type: 'number',
              description: 'A value between 0 and 255 (unsigned 8bit)',
            },
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          prompt: {
            type: 'string',
            description: 'The input text prompt for the model to generate a response.',
          },
          frequency_penalty: {
            type: 'number',
            description: 'Decreases the likelihood of the model repeating the same lines verbatim.',
          },
          lora: {
            type: 'string',
            description: 'Name of the LoRA (Low-Rank Adaptation) model to fine-tune the base model.',
          },
          max_tokens: {
            type: 'integer',
            description: 'The maximum number of tokens to generate in the response.',
          },
          presence_penalty: {
            type: 'number',
            description: 'Increases the likelihood of the model introducing new topics.',
          },
          raw: {
            type: 'boolean',
            description:
              "If true, a chat template is not applied and you must adhere to the specific model's expected formatting.",
          },
          repetition_penalty: {
            type: 'number',
            description: 'Penalty for repeated tokens; higher values discourage repetition.',
          },
          response_format: {
            type: 'object',
            title: 'JSON Mode',
            properties: {
              json_schema: {
                type: 'object',
              },
              type: {
                type: 'string',
                enum: ['json_object', 'json_schema'],
              },
            },
            required: [],
          },
          seed: {
            type: 'integer',
            description: 'Random seed for reproducibility of the generation.',
          },
          stream: {
            type: 'boolean',
            description:
              'If true, the response will be streamed back incrementally using SSE, Server Sent Events.',
          },
          temperature: {
            type: 'number',
            description: 'Controls the randomness of the output; higher values produce more random results.',
          },
          top_k: {
            type: 'integer',
            description:
              "Limits the AI to choose from the top 'k' most probable words. Lower values make responses more focused; higher values introduce more variety and potential surprises.",
          },
          top_p: {
            type: 'number',
            description:
              "Adjusts the creativity of the AI's responses by controlling how many possible words it considers. Lower values make outputs more predictable; higher values allow for more varied and creative responses.",
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          messages: {
            type: 'array',
            description: 'An array of message objects representing the conversation history.',
            items: {
              type: 'object',
              properties: {
                content: {
                  type: 'string',
                  description: 'The content of the message as a string.',
                },
                role: {
                  type: 'string',
                  description:
                    "The role of the message sender (e.g., 'user', 'assistant', 'system', 'tool').",
                },
              },
              required: ['content', 'role'],
            },
          },
          frequency_penalty: {
            type: 'number',
            description: 'Decreases the likelihood of the model repeating the same lines verbatim.',
          },
          functions: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                code: {
                  type: 'string',
                },
                name: {
                  type: 'string',
                },
              },
              required: ['code', 'name'],
            },
          },
          max_tokens: {
            type: 'integer',
            description: 'The maximum number of tokens to generate in the response.',
          },
          presence_penalty: {
            type: 'number',
            description: 'Increases the likelihood of the model introducing new topics.',
          },
          raw: {
            type: 'boolean',
            description:
              "If true, a chat template is not applied and you must adhere to the specific model's expected formatting.",
          },
          repetition_penalty: {
            type: 'number',
            description: 'Penalty for repeated tokens; higher values discourage repetition.',
          },
          response_format: {
            type: 'object',
            title: 'JSON Mode',
            properties: {
              json_schema: {
                type: 'object',
              },
              type: {
                type: 'string',
                enum: ['json_object', 'json_schema'],
              },
            },
            required: [],
          },
          seed: {
            type: 'integer',
            description: 'Random seed for reproducibility of the generation.',
          },
          stream: {
            type: 'boolean',
            description:
              'If true, the response will be streamed back incrementally using SSE, Server Sent Events.',
          },
          temperature: {
            type: 'number',
            description: 'Controls the randomness of the output; higher values produce more random results.',
          },
          tools: {
            type: 'array',
            description: 'A list of tools available for the assistant to use.',
            items: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    description: {
                      type: 'string',
                      description: 'A brief description of what the tool does.',
                    },
                    name: {
                      type: 'string',
                      description: 'The name of the tool. More descriptive the better.',
                    },
                    parameters: {
                      type: 'object',
                      description: 'Schema defining the parameters accepted by the tool.',
                      properties: {
                        properties: {
                          type: 'object',
                          description: 'Definitions of each parameter.',
                        },
                        type: {
                          type: 'string',
                          description: "The type of the parameters object (usually 'object').",
                        },
                        required: {
                          type: 'array',
                          description: 'List of required parameter names.',
                          items: {
                            type: 'string',
                          },
                        },
                      },
                      required: ['properties', 'type'],
                    },
                  },
                  required: ['description', 'name', 'parameters'],
                },
                {
                  type: 'object',
                  properties: {
                    function: {
                      type: 'object',
                      description: 'Details of the function tool.',
                      properties: {
                        description: {
                          type: 'string',
                          description: 'A brief description of what the function does.',
                        },
                        name: {
                          type: 'string',
                          description: 'The name of the function.',
                        },
                        parameters: {
                          type: 'object',
                          description: 'Schema defining the parameters accepted by the function.',
                          properties: {
                            properties: {
                              type: 'object',
                              description: 'Definitions of each parameter.',
                            },
                            type: {
                              type: 'string',
                              description: "The type of the parameters object (usually 'object').",
                            },
                            required: {
                              type: 'array',
                              description: 'List of required parameter names.',
                              items: {
                                type: 'string',
                              },
                            },
                          },
                          required: ['properties', 'type'],
                        },
                      },
                      required: ['description', 'name', 'parameters'],
                    },
                    type: {
                      type: 'string',
                      description: "Specifies the type of tool (e.g., 'function').",
                    },
                  },
                  required: ['function', 'type'],
                },
              ],
            },
          },
          top_k: {
            type: 'integer',
            description:
              "Limits the AI to choose from the top 'k' most probable words. Lower values make responses more focused; higher values introduce more variety and potential surprises.",
          },
          top_p: {
            type: 'number',
            description:
              "Adjusts the creativity of the AI's responses by controlling how many possible words it considers. Lower values make outputs more predictable; higher values allow for more varied and creative responses.",
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          target_lang: {
            type: 'string',
            description: "The language code to translate the text into (e.g., 'es' for Spanish)",
          },
          text: {
            type: 'string',
            description: 'The text to be translated',
          },
          source_lang: {
            type: 'string',
            description:
              "The language code of the source text (e.g., 'en' for English). Defaults to 'en' if not specified",
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          input_text: {
            type: 'string',
            description: 'The text that you want the model to summarize',
          },
          max_length: {
            type: 'integer',
            description: 'The maximum length of the generated summary in tokens',
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          image: {
            type: 'array',
            description:
              'An array of integers that represent the image data constrained to 8-bit unsigned integer values',
            items: {
              type: 'number',
              description: 'A value between 0 and 255',
            },
          },
          frequency_penalty: {
            type: 'number',
            description: 'Decreases the likelihood of the model repeating the same lines verbatim.',
          },
          max_tokens: {
            type: 'integer',
            description: 'The maximum number of tokens to generate in the response.',
          },
          presence_penalty: {
            type: 'number',
            description: 'Increases the likelihood of the model introducing new topics.',
          },
          prompt: {
            type: 'string',
            description: 'The input text prompt for the model to generate a response.',
          },
          raw: {
            type: 'boolean',
            description:
              "If true, a chat template is not applied and you must adhere to the specific model's expected formatting.",
          },
          repetition_penalty: {
            type: 'number',
            description: 'Penalty for repeated tokens; higher values discourage repetition.',
          },
          seed: {
            type: 'number',
            description: 'Random seed for reproducibility of the generation.',
          },
          temperature: {
            type: 'number',
            description: 'Controls the randomness of the output; higher values produce more random results.',
          },
          top_k: {
            type: 'number',
            description:
              "Limits the AI to choose from the top 'k' most probable words. Lower values make responses more focused; higher values introduce more variety and potential surprises.",
          },
          top_p: {
            type: 'number',
            description:
              "Controls the creativity of the AI's responses by adjusting how many possible words it considers. Lower values make outputs more predictable; higher values allow for more varied and creative responses.",
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          image: {
            type: 'string',
            description: 'Image in base64 encoded format.',
          },
          prompt: {
            type: 'string',
            description: 'The input text prompt for the model to generate a response.',
          },
          frequency_penalty: {
            type: 'number',
            description: 'Decreases the likelihood of the model repeating the same lines verbatim.',
          },
          ignore_eos: {
            type: 'boolean',
            description:
              'Whether to ignore the EOS token and continue generating tokens after the EOS token is generated.',
          },
          max_tokens: {
            type: 'integer',
            description: 'The maximum number of tokens to generate in the response.',
          },
          presence_penalty: {
            type: 'number',
            description: 'Increases the likelihood of the model introducing new topics.',
          },
          repetition_penalty: {
            type: 'number',
            description: 'Penalty for repeated tokens; higher values discourage repetition.',
          },
          seed: {
            type: 'number',
            description: 'Random seed for reproducibility of the generation.',
          },
          temperature: {
            type: 'number',
            description: 'Controls the randomness of the output; higher values produce more random results.',
          },
          top_k: {
            type: 'number',
            description:
              "Limits the AI to choose from the top 'k' most probable words. Lower values make responses more focused; higher values introduce more variety and potential surprises.",
          },
          top_p: {
            type: 'number',
            description:
              "Controls the creativity of the AI's responses by adjusting how many possible words it considers. Lower values make outputs more predictable; higher values allow for more varied and creative responses.",
          },
        },
      },
      {
        type: 'object',
        properties: {
          account_id: {
            type: 'string',
          },
          model_name: {
            type: 'string',
          },
          image: {
            type: 'string',
            description: 'Image in base64 encoded format.',
          },
          messages: {
            type: 'array',
            description: 'An array of message objects representing the conversation history.',
            items: {
              type: 'object',
              properties: {
                content: {
                  type: 'string',
                  description: 'The content of the message as a string.',
                },
                role: {
                  type: 'string',
                  description:
                    "The role of the message sender (e.g., 'user', 'assistant', 'system', 'tool').",
                },
              },
              required: ['content', 'role'],
            },
          },
          frequency_penalty: {
            type: 'number',
            description: 'Decreases the likelihood of the model repeating the same lines verbatim.',
          },
          ignore_eos: {
            type: 'boolean',
            description:
              'Whether to ignore the EOS token and continue generating tokens after the EOS token is generated.',
          },
          max_tokens: {
            type: 'integer',
            description: 'The maximum number of tokens to generate in the response.',
          },
          presence_penalty: {
            type: 'number',
            description: 'Increases the likelihood of the model introducing new topics.',
          },
          repetition_penalty: {
            type: 'number',
            description: 'Penalty for repeated tokens; higher values discourage repetition.',
          },
          seed: {
            type: 'number',
            description: 'Random seed for reproducibility of the generation.',
          },
          temperature: {
            type: 'number',
            description: 'Controls the randomness of the output; higher values produce more random results.',
          },
          top_k: {
            type: 'number',
            description:
              "Limits the AI to choose from the top 'k' most probable words. Lower values make responses more focused; higher values introduce more variety and potential surprises.",
          },
          top_p: {
            type: 'number',
            description:
              "Controls the creativity of the AI's responses by adjusting how many possible words it considers. Lower values make outputs more predictable; higher values allow for more varied and creative responses.",
          },
        },
      },
    ],
  },
};

export const handler = (client: Cloudflare, args: any) => {
  const { model_name, ...body } = args;
  return client.ai.run(model_name, body);
};

export default { metadata, tool, handler };
