blank_issues_enabled: false
contact_links:
  - name: v3.0.0 Beta feedback
    url: https://github.com/cloudflare/cloudflare-typescript/discussions/135
    about: |
      If you have a feature request or feedback on our new v3 library, please comment in our discussion page.
  - name: Cloudflare support
    url: https://developers.cloudflare.com/support/contacting-cloudflare-support
    about: |
      Please only file issues here that you believe represent actual bugs for the Cloudflare Typescript library.
      If you're having general trouble with the Cloudflare API, please visit our help center to get support.
