// File generated from our OpenAPI spec by Stainless.

import { APIResource } from 'cloudflare/resource';
import * as BookmarksAPI from 'cloudflare/resources/access/bookmarks';
import * as CustomPagesAPI from 'cloudflare/resources/access/custom-pages';
import * as GroupsAPI from 'cloudflare/resources/access/groups';
import * as IdentityProvidersAPI from 'cloudflare/resources/access/identity-providers';
import * as KeysAPI from 'cloudflare/resources/access/keys';
import * as OrganizationsAPI from 'cloudflare/resources/access/organizations';
import * as SeatsAPI from 'cloudflare/resources/access/seats';
import * as ServiceTokensAPI from 'cloudflare/resources/access/service-tokens';
import * as TagsAPI from 'cloudflare/resources/access/tags';
import * as ApplicationsAPI from 'cloudflare/resources/access/applications/applications';
import * as CertificatesAPI from 'cloudflare/resources/access/certificates/certificates';
import * as LogsAPI from 'cloudflare/resources/access/logs/logs';
import * as UsersAPI from 'cloudflare/resources/access/users/users';

export class Access extends APIResource {
  applications: ApplicationsAPI.Applications = new ApplicationsAPI.Applications(this._client);
  certificates: CertificatesAPI.Certificates = new CertificatesAPI.Certificates(this._client);
  groups: GroupsAPI.Groups = new GroupsAPI.Groups(this._client);
  identityProviders: IdentityProvidersAPI.IdentityProviders = new IdentityProvidersAPI.IdentityProviders(
    this._client,
  );
  organizations: OrganizationsAPI.Organizations = new OrganizationsAPI.Organizations(this._client);
  serviceTokens: ServiceTokensAPI.ServiceTokens = new ServiceTokensAPI.ServiceTokens(this._client);
  bookmarks: BookmarksAPI.Bookmarks = new BookmarksAPI.Bookmarks(this._client);
  keys: KeysAPI.Keys = new KeysAPI.Keys(this._client);
  logs: LogsAPI.Logs = new LogsAPI.Logs(this._client);
  seats: SeatsAPI.Seats = new SeatsAPI.Seats(this._client);
  users: UsersAPI.Users = new UsersAPI.Users(this._client);
  customPages: CustomPagesAPI.CustomPages = new CustomPagesAPI.CustomPages(this._client);
  tags: TagsAPI.Tags = new TagsAPI.Tags(this._client);
}

export namespace Access {
  export import Applications = ApplicationsAPI.Applications;
  export import ApplicationCreateResponse = ApplicationsAPI.ApplicationCreateResponse;
  export import ApplicationListResponse = ApplicationsAPI.ApplicationListResponse;
  export import ApplicationDeleteResponse = ApplicationsAPI.ApplicationDeleteResponse;
  export import ApplicationGetResponse = ApplicationsAPI.ApplicationGetResponse;
  export import ApplicationReplaceResponse = ApplicationsAPI.ApplicationReplaceResponse;
  export import ApplicationRevokeTokensResponse = ApplicationsAPI.ApplicationRevokeTokensResponse;
  export import ApplicationCreateParams = ApplicationsAPI.ApplicationCreateParams;
  export import ApplicationReplaceParams = ApplicationsAPI.ApplicationReplaceParams;
  export import Certificates = CertificatesAPI.Certificates;
  export import CertificateCreateResponse = CertificatesAPI.CertificateCreateResponse;
  export import CertificateListResponse = CertificatesAPI.CertificateListResponse;
  export import CertificateDeleteResponse = CertificatesAPI.CertificateDeleteResponse;
  export import CertificateGetResponse = CertificatesAPI.CertificateGetResponse;
  export import CertificateReplaceResponse = CertificatesAPI.CertificateReplaceResponse;
  export import CertificateCreateParams = CertificatesAPI.CertificateCreateParams;
  export import CertificateReplaceParams = CertificatesAPI.CertificateReplaceParams;
  export import Groups = GroupsAPI.Groups;
  export import GroupCreateResponse = GroupsAPI.GroupCreateResponse;
  export import GroupListResponse = GroupsAPI.GroupListResponse;
  export import GroupDeleteResponse = GroupsAPI.GroupDeleteResponse;
  export import GroupGetResponse = GroupsAPI.GroupGetResponse;
  export import GroupReplaceResponse = GroupsAPI.GroupReplaceResponse;
  export import GroupCreateParams = GroupsAPI.GroupCreateParams;
  export import GroupReplaceParams = GroupsAPI.GroupReplaceParams;
  export import IdentityProviders = IdentityProvidersAPI.IdentityProviders;
  export import IdentityProviderCreateResponse = IdentityProvidersAPI.IdentityProviderCreateResponse;
  export import IdentityProviderListResponse = IdentityProvidersAPI.IdentityProviderListResponse;
  export import IdentityProviderDeleteResponse = IdentityProvidersAPI.IdentityProviderDeleteResponse;
  export import IdentityProviderGetResponse = IdentityProvidersAPI.IdentityProviderGetResponse;
  export import IdentityProviderReplaceResponse = IdentityProvidersAPI.IdentityProviderReplaceResponse;
  export import IdentityProviderCreateParams = IdentityProvidersAPI.IdentityProviderCreateParams;
  export import IdentityProviderReplaceParams = IdentityProvidersAPI.IdentityProviderReplaceParams;
  export import Organizations = OrganizationsAPI.Organizations;
  export import OrganizationCreateResponse = OrganizationsAPI.OrganizationCreateResponse;
  export import OrganizationListResponse = OrganizationsAPI.OrganizationListResponse;
  export import OrganizationReplaceResponse = OrganizationsAPI.OrganizationReplaceResponse;
  export import OrganizationRevokeUsersResponse = OrganizationsAPI.OrganizationRevokeUsersResponse;
  export import OrganizationCreateParams = OrganizationsAPI.OrganizationCreateParams;
  export import OrganizationReplaceParams = OrganizationsAPI.OrganizationReplaceParams;
  export import OrganizationRevokeUsersParams = OrganizationsAPI.OrganizationRevokeUsersParams;
  export import ServiceTokens = ServiceTokensAPI.ServiceTokens;
  export import ServiceTokenCreateResponse = ServiceTokensAPI.ServiceTokenCreateResponse;
  export import ServiceTokenListResponse = ServiceTokensAPI.ServiceTokenListResponse;
  export import ServiceTokenDeleteResponse = ServiceTokensAPI.ServiceTokenDeleteResponse;
  export import ServiceTokenRefreshResponse = ServiceTokensAPI.ServiceTokenRefreshResponse;
  export import ServiceTokenReplaceResponse = ServiceTokensAPI.ServiceTokenReplaceResponse;
  export import ServiceTokenRotateResponse = ServiceTokensAPI.ServiceTokenRotateResponse;
  export import ServiceTokenCreateParams = ServiceTokensAPI.ServiceTokenCreateParams;
  export import ServiceTokenReplaceParams = ServiceTokensAPI.ServiceTokenReplaceParams;
  export import Bookmarks = BookmarksAPI.Bookmarks;
  export import BookmarkListResponse = BookmarksAPI.BookmarkListResponse;
  export import BookmarkDeleteResponse = BookmarksAPI.BookmarkDeleteResponse;
  export import BookmarkGetResponse = BookmarksAPI.BookmarkGetResponse;
  export import BookmarkReplaceResponse = BookmarksAPI.BookmarkReplaceResponse;
  export import Keys = KeysAPI.Keys;
  export import KeyListResponse = KeysAPI.KeyListResponse;
  export import KeyReplaceResponse = KeysAPI.KeyReplaceResponse;
  export import KeyRotateResponse = KeysAPI.KeyRotateResponse;
  export import KeyReplaceParams = KeysAPI.KeyReplaceParams;
  export import Logs = LogsAPI.Logs;
  export import Seats = SeatsAPI.Seats;
  export import SeatUpdateResponse = SeatsAPI.SeatUpdateResponse;
  export import SeatUpdateParams = SeatsAPI.SeatUpdateParams;
  export import Users = UsersAPI.Users;
  export import UserListResponse = UsersAPI.UserListResponse;
  export import CustomPages = CustomPagesAPI.CustomPages;
  export import CustomPageCreateResponse = CustomPagesAPI.CustomPageCreateResponse;
  export import CustomPageListResponse = CustomPagesAPI.CustomPageListResponse;
  export import CustomPageDeleteResponse = CustomPagesAPI.CustomPageDeleteResponse;
  export import CustomPageGetResponse = CustomPagesAPI.CustomPageGetResponse;
  export import CustomPageReplaceResponse = CustomPagesAPI.CustomPageReplaceResponse;
  export import CustomPageCreateParams = CustomPagesAPI.CustomPageCreateParams;
  export import CustomPageReplaceParams = CustomPagesAPI.CustomPageReplaceParams;
  export import Tags = TagsAPI.Tags;
  export import TagCreateResponse = TagsAPI.TagCreateResponse;
  export import TagListResponse = TagsAPI.TagListResponse;
  export import TagDeleteResponse = TagsAPI.TagDeleteResponse;
  export import TagGetResponse = TagsAPI.TagGetResponse;
  export import TagReplaceResponse = TagsAPI.TagReplaceResponse;
  export import TagCreateParams = TagsAPI.TagCreateParams;
  export import TagReplaceParams = TagsAPI.TagReplaceParams;
}
