#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Detecting breaking changes"

TEST_PATHS=(
	tests/api-resources/cache/cache.test.ts
	tests/api-resources/cache/cache-reserve.test.ts
	tests/api-resources/cache/smart-tiered-cache.test.ts
	tests/api-resources/cache/variants.test.ts
	tests/api-resources/cache/regional-tiered-cache.test.ts
	tests/api-resources/cache/origin-cloud-regions.test.ts
	tests/api-resources/argo/argo.test.ts
	tests/api-resources/argo/tiered-caching.test.ts
	tests/api-resources/origin-post-quantum-encryption.test.ts
	tests/index.test.ts
)

for PATHSPEC in "${TEST_PATHS[@]}"; do
    # Try to check out previous versions of the test files
    # with the current SDK.
    git checkout "$1" -- "${PATHSPEC}" 2>/dev/null || true
done

# Instead of running the tests, use the linter to check if an
# older test is no longer compatible with the latest SDK.
./scripts/lint
